### ISSUE TITLE
JavaDB legyen vagy oracle

### ISSUE THREAD

**Issue by akooos** [vasicsek/ELTE-IK-PE-orarend#1]
Korábban probléma volt JavaDB-vel,
úgy tűnik most már külön fel kell telepíteni Glassfish-t a gépre és a netbeans-ben
Services->JavaDB->properties ablakban megadni a javadb server helyét,
hogy működjön. 
Kérdésem: ha mindenkinek sikerült beüzemelni a JavaDB-t, 
akkor inkább használjuk ezt mint adatbázist kezelőt
és eltávolítsam az oracle függőséget?

**Comment by gvasicsek** [comment]
Én JavaDB-re szavazok. Nekem ugye volt problémám a másik két adatbázissal. :)

**Comment by dobi79** [comment]
Sziasztok!
Nekem is megfelel a JavaDB! Akkor szerintem használjuk a JavaDB-t úgyis
eredetileg is azt akartuk használni!

**Comment by akooos** [comment]
Sziasztok! 
Újratelepítettem a windowsomat. Netbeans installálásnál érdemes a Java EE 192 MB letölteni, mivel ez már tartalmaz GlassFish Open Source Edition-t. Netbeansben a Services->Java DB->Properties Java DB installation mezőnek meg kell adni glasshfish java db elérési útvonalát. Nálam ez "C:\Program Files\glassfish-4.1.1\javadb".
és a maven pom.xml-hez hozzá kellett adni:

```
<dependency>
<groupId>org.apache.derby</groupId>
<artifactId>derbyclient</artifactId>
<version>10.12.1.1</version>
</dependency>
```

Így most már nálam is működik a Java DB.
